### ISSUE TITLE
Unable to run bmlingam-coeff

### ISSUE THREAD

**Issue by code-rana** [taku-y/bmlingam#8]
I have installed bmlingam which works great finding causality .
However I am facing the following issue while running bmlingam-coeff.
```
Traceback (most recent call last):
File "/home/administrator/anaconda2/bin/bmlingam-coeff", line 11, in <module>
from bmlingam.commands.bmlingam_coeff import estimate_coeff_posterior, \
ImportError: cannot import name estimate_coeff_posterior
```
Can you please help what must have gone wrong

**Comment by taku-y** [comment]
Hi @abhishekscript Thanks for your report. I fixed a bug on your problem and pushed to `develop` branch. Could you try this?
