### ISSUE TITLE
Can we resume BMLiNGAM 

### ISSUE THREAD

**Issue by code-rana** [taku-y/bmlingam#9]
The CSV file I am giving has 37 variables out of which few have been processed and log has been captured, but suddenly my system crashed.
Now in my logs I can see
{
  2 * log(p(M)) - log(p(M_rev)) : 22.123
 Infered Causality : "A->B"
}
Is there a way to resume BMLiNGAM where the program last left with ?

**Comment by taku-y** [comment]
@abhishekscript Sorry, BMLiNGAM doesn't support resume from terminations like system crash. I will implements some mechanism to support that. I think it is enough for resuming to save the result of each of all variable pairs during causal inference. Sorry again for inconvenience on the current version.
